# Name : RUPA FADIKAR

# COGNIFYZ Internship Task : Business Analytics

# Task-3: Descriptive Statistics
# Objective: Present basic statistics for numerical columns

In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("Data_set 2 - Copy.csv")

In [3]:
# First 5 rows from Dataset
print("First 5 Rows :")
df.head(5)

First 5 Rows :

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [4]:
# 1.Identify Numerical Columns
numeric_columns = df.select_dtypes(include=['number'])
print("All Numeric columns :\n")
numeric_columns

All Numeric columns :

,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
0,34,1,2,5,3,7,6,4
1,23,4,3,2,1,5,6,7
2,30,3,6,4,2,5,1,7
3,22,2,1,3,7,6,4,5
4,24,2,1,3,6,4,5,7
5,24,7,5,4,6,3,1,2
6,27,3,6,4,2,5,1,7
7,21,2,3,7,4,6,1,5
8,35,2,4,7,5,3,1,6
9,31,1,3,7,4,5,2,6
10,35,2,4,7,5,3,1,6
11,29,2,5,7,6,3,1,4
12,21,1,2,3,4,5,6,7
13,28,2,3,7,4,5,1,6
14,25,2,3,7,5,4,1,6
15,27,2,3,7,5,4,1,6
16,28,3,2,7,5,4,1,6
17,27,3,2,7,4,5,1,6
18,29,3,2,7,4,5,1,6
19,26,3,4,6,5,1,2,7
20,29,2,4,7,5,3,1,6
21,24,2,4,5,6,3,1,7
22,27,3,4,6,5,2,1,7
23,25,2,4,6,5,3,1,7
24,26,2,3,7,5,4,1,6
25,32,3,4,7,5,1,2,6
26,26,3,4,6,5,1,2,7
27,31,2,3,7,6,4,1,5
28,29,2,3,6,5,1,4,7
29,34,5,4,3,2,7,1,6
30,27,4,5,1,2,7,3,6
31,31,2,4,7,6,3,1,5
32,27,2,4,7,5,1,3,6
33,26,2,3,6,4,1,5,7
34,27,2,3,6,5,4,1,7
35,30,1,4,6,5,3,2,7
36,30,2,4,7,5,1,3,6
37,25,5,4,7,6,1,2,3
38,31,2,4,7,5,3,1,6
39,29,4,3,5,7,2,1,6

In [5]:
# Total numeric columns
count = len(df.select_dtypes(include=['number']).columns)
print("Total Numeric columns :",count)

Total Numeric columns : 8

In [6]:
# 2.Statistical Calculations
print("Statistical Calculations for each numerical column\n")
numeric_columns.describe()

Statistical Calculations for each numerical column

,age,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,27.800000,2.550000,3.475000,5.750000,4.650000,3.575000,2.025000,5.975000
std,3.560467,1.197219,1.131994,1.675617,1.369072,1.795828,1.609069,1.143263
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,25.750000,2.000000,3.000000,5.000000,4.000000,2.750000,1.000000,6.000000
50%,27.000000,2.000000,4.000000,6.500000,5.000000,3.500000,1.000000,6.000000
75%,30.000000,3.000000,4.000000,7.000000,5.000000,5.000000,2.250000,7.000000
max,35.000000,7.000000,6.000000,7.000000,7.000000,7.000000,6.000000,7.000000